# Generated by Django 3.2.15 on 2022-10-01 13:20

from django.db import migrations


def transfer_back(apps, schema_editor):
    News = apps.get_model("mainapp", "News")
    Interim_news = apps.get_model("mainapp", "Interim_news")
    list_of_ids = Interim_news.objects.values_list("id", flat=True)
    list_of_bodies = Interim_news.objects.values_list("body", flat=True)
    for item_id, item_body in zip(list_of_ids, list_of_bodies):
        News.objects.update_or_create(id=item_id, defaults={"body": item_body})


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_truncate_news"),
    ]

    operations = [migrations.RunPython(transfer_back)]
