# Generated by Django 3.2.15 on 2022-10-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_transfer_back"),
    ]

    operations = [migrations.DeleteModel("Interim_news")]
